# build version
version: 'build #{build}'

# branches to build
branches:
  # blacklist
  except:
  - gh-pages
  - travis
  - appveyor

# Do not build on tags
skip_tags: true

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk10
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

# install required tools
install:
- cmd: echo %JAVA_HOME%
- cmd: SET JAVA_OPTS=-Dhttps.protocols=TLSv1.2

# build and install artifacts
build_script:
- ./gradlew clean build --no-daemon

# verify artifacts
test_script:
- ./gradlew clean test --no-daemon


artifacts:
- path: build\libs\*
  name: build

# preserve dependencies between builds
cache:
- C:/Users/appveyor/.gradle