language: java

# Faster builds
sudo: false

env:
  global:
  - JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"
  - SCAN="--scan --stacktrace --warning-mode=all"
  # JDK_JAVA_OPTIONS='--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED'

matrix:
  include:
  - os: linux
    jdk: openjdk10
    env: JACOCO='jacocoTestReport'
  - os: linux
    jdk: openjdk11
  - os: linux
    jdk: openjdk-ea

  - os: osx
    jdk: openjdk10
    env: JACOCO='jacocoTestReport'
  - os: osx
    jdk: openjdk11
  - os: osx
    jdk: openjdk-ea

  allow_failures:
  - jdk: openjdk11
  - jdk: openjdk-ea

# os:
# - linux
# - osx
#
# jdk:
# - openjdk10
# - openjdk11

before_script:
- chmod +x gradlew

script:
- echo $HOME
- echo $JAVA_OPTS
- ./gradlew --version
- ./gradlew clean ${JACOCO} build --no-daemon

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

after_success:
- bash <(curl -s https://codecov.io/bash)