language: java
sudo: false

env:
  global:
    - JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"
    - SCAN="--scan --stacktrace --warning-mode=all"

before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
    - stage: 🍺 OpenJDK - Linux + Mac + Windows
      os: linux
      env:
        - JDK=11
        - JACOCO='jacocoTestReport'
      jdk: openjdk11
    - os: osx
      env: JDK=11
      jdk: openjdk11
    - os: windows
      env: JDK=11
      jdk: openjdk11

    - stage: ☕ jdk.java.net - OpenJDK - GPL
      env: JDK=11
      script: source install-jdk.sh -F 11
    - env: JDK=12
      script: source install-jdk.sh -F 12

    - stage: 🚀 GraalVM CE
      env:
        - GRAALVM_VERSION=1.0.0-rc13
        - JDK=graalvm-ce-$GRAALVM_VERSION
      script: source install-jdk.sh --url https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$GRAALVM_VERSION-linux-amd64.tar.gz

  allow_failures:
    - os: windows
    - jdk: JDK=13

script:
  - echo $HOME
  - echo $JAVA_OPTS

after_script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - echo PATH = ${PATH}
  - ls ${JAVA_HOME}
  - java -version
  - ./gradlew clean ${JACOCO} publish

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: change

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/